### ISSUE TITLE
User: Update existing submission to the library.

### ISSUE THREAD

**Issue by sinatra-ms** [sinatra-pod/moringa-library#11]

**Comment by mutuajoseph** [comment]
Submission by what time => EOD -> check on this tomorrow morning

**Comment by otsembo** [comment]
Hello @karume629 
I have not seen your update on this.

**Comment by karume629** [comment]
I have moved them to the review area, i have scheduled a review with @mutuajoseph

**Comment by karume629** [comment]
![Image](https://user-images.githubusercontent.com/67807019/223964612-7d0a6e23-df7b-4412-aa74-e24a65743654.png)

@otsembo

**Comment by otsembo** [comment]
@karume629 Here are a few changes:

- [ ] Input fields do not match our design system. Use the one with `title` as the default style.
- [ ] Buttons should also match our design system. Use the one on the `Visitor: Viewing submissions` page.
- [ ] `Add Tech Stack` button should be a dropdown as opposed to a button with a plus sign.
- [ ] Height of `[title, category, repository, livelink]` text fields should be the same size (h x w)
- [ ] **Select Image** button should fit the card width that is wrapping it.
- [ ] Use appropriate footer
- [ ] Description, should have a rich textarea similar to this one:
![Image](https://user-images.githubusercontent.com/38042565/225423589-320d3933-6a24-4fdf-a203-b43cad6153bc.png)
- [ ] Kindly use an alternate to the checkboxes if you intend to indicate the progress of a submission. Check out a sample:
![Image](https://user-images.githubusercontent.com/38042565/225424529-417f8757-731c-4a1c-969b-98d5ba5400fe.png)

**Comment by karume629** [comment]
@otsembo I have updated the changes.

**Comment by karume629** [comment]
![Image](https://user-images.githubusercontent.com/67807019/225980808-047a4d83-fe47-44f4-900b-8f8a64f34ad5.png)

@otsembo

**Comment by otsembo** [comment]
Good Job @karume629
