### ISSUE TITLE
User: Comment and rate existing project in the library.

### ISSUE THREAD

**Issue by sinatra-ms** [sinatra-pod/moringa-library#14]

**Comment by mutuajoseph** [comment]
link to be submitted by 4:30pm today

**Comment by KelvinMuriithi** [comment]
https://www.figma.com/file/bnJw1TntsQCzGDeDWsg0V5/Moringa-Library?node-id=130%3A25&t=FgbLfBv1YIJnQyFn-1 @mutuajoseph @Albert-Byrone # @sinatra-ms

**Comment by KelvinMuriithi** [comment]
[Link](https://www.figma.com/file/bnJw1TntsQCzGDeDWsg0V5/Moringa-Library?node-id=410%3A4065&t=qBRHZBLdepWVn3t2-1)
