### ISSUE TITLE
Reviewer: Add review to the submission including approval / rejection.

### ISSUE THREAD

**Issue by sinatra-ms** [sinatra-pod/moringa-library#16]

**Comment by mutuajoseph** [comment]
Submission by what time => EOD -> check on this tomorrow morning

**Comment by otsembo** [comment]
Hello @karume629 
I have not seen your update on this task.

**Comment by Albert-Byrone** [comment]
Hello @karume629 , Here are a few changes to fix

- [ ] The frame does not fit the required screen
- [ ] Use the appropriate navbar
- [ ] Comments sections should be a rich text area
   
![Image](https://user-images.githubusercontent.com/30287402/225426165-c084196c-f933-410f-b17b-304d0b89ff53.png)

- [ ] Replace the status section with actual radio buttons

![Image](https://user-images.githubusercontent.com/30287402/225426779-84415671-9280-404a-a5ad-c69d5ef6eef0.png)


- [ ] Fix the buttons to match the design pattern
- [ ] Add a footer to the page

**Comment by karume629** [comment]
![Image](https://user-images.githubusercontent.com/67807019/225980128-8da7c344-f0e5-48f4-8fd0-100d3e4a8b44.png)

@Albert-Byrone  Check out the requested changes

**Comment by otsembo** [comment]
Great job @karume629
