### ISSUE TITLE
Admin: Delete account for reviewer.

### ISSUE THREAD

**Issue by sinatra-ms** [sinatra-pod/moringa-library#18]

**Comment by otsembo** [comment]
@mutuajoseph I have made an update for this.

**Comment by otsembo** [comment]
![Image](https://user-images.githubusercontent.com/38042565/223025276-05160098-213b-4fdc-baf4-97f6409af9b9.png)

**Comment by mutuajoseph** [comment]
Loving the design so far.

Quick question: Can the tech stack session logos be replaced with actual language logos.

**Comment by otsembo** [comment]
I have added the logos.
![Image](https://user-images.githubusercontent.com/38042565/223051568-4c5c8985-e1f5-45c9-b4ca-bb132244866e.png)
