### ISSUE TITLE
Admin: Accept / Reject Submission to the library.

### ISSUE THREAD

**Issue by sinatra-ms** [sinatra-pod/moringa-library#19]

**Comment by mutuajoseph** [comment]
link to be submitted by 4:30pm today

**Comment by KelvinMuriithi** [comment]
[Link](https://www.figma.com/file/bnJw1TntsQCzGDeDWsg0V5/Moringa-Library?node-id=436%3A4230&t=qBRHZBLdepWVn3t2-1) @mutuajoseph @Albert-Byrone

**Comment by mutuajoseph** [comment]
1. Replace the navbar to fit the ones in the design
2. Page design should fit the screen size without looking like it's zoomed in.
3. Place sample information of the project details
4. Place an image of the project in an appropriate place that fits the page.
5. Admin should be able to see what project reviewers commented so as to make the final decision.

**Comment by otsembo** [comment]
Have a review requested by 17th March 2023 2:00PM

**Comment by KelvinMuriithi** [comment]
[Link](https://www.figma.com/file/bnJw1TntsQCzGDeDWsg0V5/Moringa-Library?node-id=436%3A4230&t=UrqbguwYaFdf3QYz-1)

**Comment by otsembo** [comment]
Good Job @KelvinMuriithi
