### ISSUE TITLE
Database: Create Migrations (User, Tech Stacks, Projects, Project Comments)

### ISSUE THREAD

**Issue by otsembo** [sinatra-pod/moringa-library#30]
- Create the migrations for the first two tables. 
- Add columns and set up enums

**Comment by otsembo** [comment]
- Create the migrations for the first two tables. 
- Add columns and set up enums

**Comment by kiprotichdominic** [comment]
Created Migrations for all the models

**Comment by kiprotichdominic** [comment]
seems all models match as per the schema design
