### ISSUE TITLE
Visitor: Home Page

### ISSUE THREAD

**Issue by sinatra-ms** [sinatra-pod/moringa-library#4]

**Comment by otsembo** [comment]
@Calebbii As agreed upon earlier, you were:

- [ ] Attach the new navbar
- [ ] Add an intro section
- [ ] List of top projects should be placed in a container. (ALternatively we could have a piece explaining how to make a submission)
- [ ] Have 3 cards and ensure you use the card template I provided.
- [ ] Add a section for a video. (Pick a random youtube video for now)
- [ ] Attach the new footer

**Comment by otsembo** [comment]
@Calebbii Ensure you attach the final screenshot
