### ISSUE TITLE
Font selection

### ISSUE THREAD

**Issue by otsembo** [sinatra-pod/moringa-library#40]
Pick a font that will be used for the entire front-end application

**Comment by otsembo** [comment]
Font Selection Meeting: https://meet.google.com/fsy-rpbg-jow

**Comment by mutuajoseph** [comment]
@otsembo 

Hey Ive been doing some RnD today and settled withe the two fonts below:

1. Roboto => https://fonts.google.com/specimen/Roboto
2. Poppins => https://fonts.google.com/specimen/Poppins
