### ISSUE TITLE
Visitor: Projects search page

### ISSUE THREAD

**Issue by sinatra-ms** [sinatra-pod/moringa-library#5]

**Comment by otsembo** [comment]
@Dachoka3000 
I could not see the search bar in the frames.

**Comment by Dachoka3000** [comment]
![searcherpage](https://user-images.githubusercontent.com/67946732/224101121-02b8490a-2c9c-4641-a6b4-e3c5108afdc9.png)

**Comment by otsembo** [comment]
@Albert-Byrone , @Dachoka3000  Align the two pages.

**Comment by Albert-Byrone** [comment]
@Albert-Byrone @Dachoka3000 

Where are the changes for this?

**Comment by Dachoka3000** [comment]
![Image](https://user-images.githubusercontent.com/67946732/225632958-c2002acf-0028-4240-9c59-89485ad36bc0.png)

@Albert-Byrone
