### ISSUE TITLE
Visitor: User create a new account.

### ISSUE THREAD

**Issue by sinatra-ms** [sinatra-pod/moringa-library#7]

**Comment by otsembo** [comment]
Good Job @Calebbii 
Find the following minor fixes:

- [ ] Replace `Your e-mail` with `EMAIL`
![Image](https://user-images.githubusercontent.com/38042565/222404023-afcf5fa6-b247-495e-8c45-873ec4fdd68d.png)


- [ ] Replace the second `PASSWORD` with `CONFIRM PASSWORD`
![Image](https://user-images.githubusercontent.com/38042565/222404317-f8544871-1abc-48f0-8c20-fed1e6ab8baa.png)

- [ ] Google sign in Logo should look like this:
![Image](https://user-images.githubusercontent.com/38042565/222404538-6a0025b7-e69b-48a3-a22c-1c7ba8ade284.png)

**Comment by Calebbii** [comment]
I have fixed the changes

**Comment by otsembo** [comment]
![Image](https://user-images.githubusercontent.com/38042565/223603599-dbc66a13-602c-4627-82a8-d98bcf6645d2.png)

**Comment by otsembo** [comment]
@Calebbii Ensure you attach the final screenshot
