### ISSUE TITLE
User: Add new submission to the library.

### ISSUE THREAD

**Issue by sinatra-ms** [sinatra-pod/moringa-library#9]

**Comment by kiprotichdominic** [comment]
Done.

**Comment by kiprotichdominic** [comment]
@mutuajoseph  please review and feedback on 
the same 
https://www.figma.com/file/bnJw1TntsQCzGDeDWsg0V5/Moringa-Library?node-id=227%3A2520&t=YjNUjAiGkMoBvrNj-0

**Comment by kiprotichdominic** [comment]
![Image](https://user-images.githubusercontent.com/55743569/223964219-2871ab61-757e-4fed-b749-beea10592415.png)

**Comment by Albert-Byrone** [comment]
Hello @kiprotichdominic Here are some changes

- [ ] Update the footer to match the one used on all pages
- [ ] Update the button to match the one used on all pages
